import React, { useState, useEffect } from 'react';
import { 
  ArrowLeft, 
  Printer, 
  Download, 
  Filter,
  CheckCircle2,
  Calendar,
  User,
  GraduationCap
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const AdmissionReport = ({ user }) => {
  const [admissions, setAdmissions] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchAdmissions = async () => {
      try {
        const token = localStorage.getItem('token');
        const response = await fetch('http://localhost:3000/finance/students', {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        if (response.ok) {
          const data = await response.json();
          // Filter only students who have paid the admission fee
          const paidStudents = data.filter(student => student.admission_fee === 'Yes');
          setAdmissions(paidStudents);
        }
      } catch (error) {
        console.error('Error fetching report data:', error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchAdmissions();
  }, []);

  if (isLoading) {
    return (
      <div className="h-screen flex items-center justify-center bg-white">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin"></div>
          <p className="text-sm font-black text-slate-900 uppercase tracking-widest">Generating Report...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 p-8 md:p-12 print:p-0 print:bg-white">
      {/* Header - Hidden on print */}
      <div className="max-w-7xl mx-auto mb-10 flex flex-col md:flex-row md:items-center justify-between gap-6 print:hidden">
        <div className="flex items-center gap-4">
          <button 
            onClick={() => navigate(-1)}
            className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center text-slate-400 hover:text-indigo-600 hover:shadow-lg transition-all"
          >
            <ArrowLeft size={20} />
          </button>
          <div>
            <h1 className="text-3xl font-black text-slate-900 tracking-tight">Admission Report</h1>
            <p className="text-xs text-slate-400 font-bold uppercase tracking-widest mt-1">Confirmed Enrollments Only</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={() => window.print()}
            className="px-6 py-3 bg-slate-900 text-white text-[11px] font-black rounded-xl shadow-xl shadow-slate-900/20 tracking-widest uppercase flex items-center gap-2 hover:translate-y-[-2px] transition-all"
          >
            <Printer size={16} />
            Print Report
          </button>
          <button className="px-6 py-3 bg-white border border-slate-200 text-slate-900 text-[11px] font-black rounded-xl hover:bg-slate-50 tracking-widest uppercase flex items-center gap-2 transition-all">
            <Download size={16} />
            Export PDF
          </button>
        </div>
      </div>

      {/* Report Container */}
      <div className="max-w-7xl mx-auto bg-white rounded-[3rem] shadow-[0_20px_50px_-20px_rgba(0,0,0,0.05)] border border-slate-100 overflow-hidden print:shadow-none print:border-none print:rounded-none">
        {/* Report Top Branding */}
        <div className="p-12 border-b-4 border-indigo-600 bg-slate-900 text-white relative overflow-hidden">
          <div className="absolute top-[-50%] right-[-10%] w-96 h-96 bg-indigo-600/20 rounded-full blur-3xl"></div>
          <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-8">
            <div>
              <h2 className="text-4xl font-black tracking-tighter mb-2">VFSTR UNIVERSITY</h2>
              <p className="text-indigo-400 font-bold uppercase tracking-[0.3em] text-xs">Official Admission Ledger • 2026-27</p>
            </div>
            <div className="text-left md:text-right">
              <p className="text-sm font-bold text-slate-300">Generated By: <span className="text-white capitalize">{user?.user?.username || user?.username}</span></p>
              <p className="text-sm font-bold text-slate-300">Date: <span className="text-white">{new Date().toLocaleDateString()}</span></p>
              <div className="mt-4 inline-flex items-center gap-2 px-3 py-1 bg-emerald-500/20 text-emerald-400 rounded-lg text-[10px] font-black uppercase tracking-widest border border-emerald-500/20">
                <CheckCircle2 size={12} />
                Verified Status
              </div>
            </div>
          </div>
        </div>

        {/* Report Stats Summary */}
        <div className="grid grid-cols-1 md:grid-cols-3 border-b border-slate-50 divide-x divide-slate-50">
          <div className="p-10 flex items-center gap-6">
            <div className="w-14 h-14 bg-indigo-50 rounded-2xl flex items-center justify-center text-indigo-600">
              <GraduationCap size={28} />
            </div>
            <div>
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Total Confirmed</p>
              <h4 className="text-3xl font-black text-slate-900">{admissions.length}</h4>
            </div>
          </div>
          <div className="p-10 flex items-center gap-6">
            <div className="w-14 h-14 bg-amber-50 rounded-2xl flex items-center justify-center text-amber-600">
              <Calendar size={28} />
            </div>
            <div>
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Academic Year</p>
              <h4 className="text-2xl font-black text-slate-900">2026-2027</h4>
            </div>
          </div>
          <div className="p-10 flex items-center gap-6">
            <div className="w-14 h-14 bg-emerald-50 rounded-2xl flex items-center justify-center text-emerald-600">
              <User size={28} />
            </div>
            <div>
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Reporting Officer</p>
              <h4 className="text-lg font-black text-slate-900 capitalize">{user?.user?.username || user?.username}</h4>
            </div>
          </div>
        </div>

        {/* Data Table */}
        <div className="overflow-x-auto p-4 md:p-10">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50/50">
                <th className="px-8 py-6 text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-slate-100">S.No</th>
                <th className="px-8 py-6 text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-slate-100">Register No</th>
                <th className="px-8 py-6 text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-slate-100">Student Name</th>
                <th className="px-8 py-6 text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-slate-100">Course & Branch</th>
                <th className="px-8 py-6 text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-slate-100">VUID</th>
                <th className="px-8 py-6 text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-slate-100">Admission Fee</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {admissions.length > 0 ? (
                admissions.map((student, index) => (
                  <tr key={student.vuid} className="hover:bg-slate-50/30 transition-colors">
                    <td className="px-8 py-5 text-sm font-bold text-slate-400">{index + 1}</td>
                    <td className="px-8 py-5">
                      <span className="text-sm font-black text-slate-900 tracking-tight">{student.registerno}</span>
                    </td>
                    <td className="px-8 py-5">
                      <div className="flex flex-col">
                        <span className="text-sm font-black text-slate-900">{student.name}</span>
                        <span className="text-[10px] text-slate-400 font-bold uppercase">{student.gender}</span>
                      </div>
                    </td>
                    <td className="px-8 py-5">
                      <div className="flex flex-col">
                        <span className="text-xs font-black text-slate-700">{student.coursecode}</span>
                        <span className="text-[10px] text-slate-400 font-bold uppercase">{student.branchcode}</span>
                      </div>
                    </td>
                    <td className="px-8 py-5">
                      <span className="px-3 py-1 bg-slate-50 border border-slate-100 rounded-lg text-[10px] font-black font-mono text-slate-600">
                        {student.vuid}
                      </span>
                    </td>
                    <td className="px-8 py-5">
                      <div className="flex items-center gap-2 text-emerald-600">
                        <CheckCircle2 size={14} />
                        <span className="text-[10px] font-black uppercase tracking-widest">Paid</span>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="6" className="px-8 py-20 text-center">
                    <div className="flex flex-col items-center gap-4 grayscale opacity-30">
                      <Printer size={64} />
                      <p className="text-sm font-black text-slate-500 uppercase tracking-widest">No confirmed admissions found for this criteria.</p>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* Report Footer */}
        <div className="p-12 bg-slate-50/50 border-t border-slate-100 flex flex-col md:flex-row justify-between items-center gap-10">
          <div className="text-center md:text-left">
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">Verification Seal</p>
            <div className="w-32 h-32 border-4 border-double border-slate-200 rounded-full flex items-center justify-center flex-col opacity-50">
              <CheckCircle2 size={32} className="text-slate-200" />
              <span className="text-[8px] font-black uppercase text-slate-300">VFSTR LEDGER</span>
            </div>
          </div>
          <div className="text-center md:text-right space-y-2">
            <div className="w-64 h-px bg-slate-200 mb-8 mx-auto md:ml-auto md:mr-0"></div>
            <p className="text-sm font-black text-slate-900">Authorized Signature</p>
            <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Registrar / Admission Head</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdmissionReport;
